routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('testNames', App\Http\Controllers\TestNameController::class);

Route::resource('testNames', App\Http\Controllers\TestNameController::class);

Route::resource('users', App\Http\Controllers\UserController::class)->middleware('auth');

app/Models/TestName.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class TestName
 * @package App\Models
 * @version November 4, 2020, 12:09 pm UTC
 *
 * @property string $title
 * @property string $body
 * @property string $email
 * @property integer $writer_id
 */
class TestName extends Model
{
    use SoftDeletes;

    public $table = 'test_names';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'title',
        'body',
        'email',
        'writer_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'body' => 'string',
        'email' => 'string',
        'writer_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/TestNameController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTestNameRequest;
use App\Http\Requests\UpdateTestNameRequest;
use App\Repositories\TestNameRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class TestNameController extends AppBaseController
{
    /** @var  TestNameRepository */
    private $testNameRepository;

    public function __construct(TestNameRepository $testNameRepo)
    {
        $this->testNameRepository = $testNameRepo;
    }

    /**
     * Display a listing of the TestName.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $testNames = $this->testNameRepository->all();

        return view('test_names.index')
            ->with('testNames', $testNames);
    }

    /**
     * Show the form for creating a new TestName.
     *
     * @return Response
     */
    public function create()
    {
        return view('test_names.create');
    }

    /**
     * Store a newly created TestName in storage.
     *
     * @param CreateTestNameRequest $request
     *
     * @return Response
     */
    public function store(CreateTestNameRequest $request)
    {
        $input = $request->all();

        $testName = $this->testNameRepository->create($input);

        Flash::success('Test Name saved successfully.');

        return redirect(route('testNames.index'));
    }

    /**
     * Display the specified TestName.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $testName = $this->testNameRepository->find($id);

        if (empty($testName)) {
            Flash::error('Test Name not found');

            return redirect(route('testNames.index'));
        }

        return view('test_names.show')->with('testName', $testName);
    }

    /**
     * Show the form for editing the specified TestName.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $testName = $this->testNameRepository->find($id);

        if (empty($testName)) {
            Flash::error('Test Name not found');

            return redirect(route('testNames.index'));
        }

        return view('test_names.edit')->with('testName', $testName);
    }

    /**
     * Update the specified TestName in storage.
     *
     * @param int $id
     * @param UpdateTestNameRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTestNameRequest $request)
    {
        $testName = $this->testNameRepository->find($id);

        if (empty($testName)) {
            Flash::error('Test Name not found');

            return redirect(route('testNames.index'));
        }

        $testName = $this->testNameRepository->update($request->all(), $id);

        Flash::success('Test Name updated successfully.');

        return redirect(route('testNames.index'));
    }

    /**
     * Remove the specified TestName from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $testName = $this->testNameRepository->find($id);

        if (empty($testName)) {
            Flash::error('Test Name not found');

            return redirect(route('testNames.index'));
        }

        $this->testNameRepository->delete($id);

        Flash::success('Test Name deleted successfully.');

        return redirect(route('testNames.index'));
    }
}

resources/views/test_names/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Test Name
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'testNames.store']) !!}

                        @include('test_names.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/test_names/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Test Name
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($testName, ['route' => ['testNames.update', $testName->id], 'method' => 'patch']) !!}

                        @include('test_names.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/test_names/fields.blade.php
<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<!-- Body Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('body', 'Body:') !!}
    {!! Form::textarea('body', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Writer Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('writer_id', 'Writer Id:') !!}
    {!! Form::text('writer_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('testNames.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/test_names/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Test Names</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('testNames.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('test_names.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/test_names/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Test Name
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('test_names.show_fields')
                    <a href="{{ route('testNames.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/test_names/show_fields.blade.php
<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <p>{{ $testName->title }}</p>
</div>

<!-- Body Field -->
<div class="form-group">
    {!! Form::label('body', 'Body:') !!}
    <p>{{ $testName->body }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $testName->email }}</p>
</div>

<!-- Writer Id Field -->
<div class="form-group">
    {!! Form::label('writer_id', 'Writer Id:') !!}
    <p>{{ $testName->writer_id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $testName->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $testName->updated_at }}</p>
</div>

resources/views/test_names/table.blade.php
<div class="table-responsive">
    <table class="table" id="testNames-table">
        <thead>
            <tr>
                <th>Title</th>
        <th>Email</th>
        <th>Writer Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($testNames as $testName)
            <tr>
                <td>{{ $testName->title }}</td>
            <td>{{ $testName->email }}</td>
            <td>{{ $testName->writer_id }}</td>
                <td>
                    {!! Form::open(['route' => ['testNames.destroy', $testName->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('testNames.show', [$testName->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('testNames.edit', [$testName->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>